# External link checker configuration for world_time
DirectoryPath: "public"
FileExtension: ".html"

# Only check external links
CheckExternal: true
CheckInternal: false
CheckInternalHash: false

# Basic checks
CheckDoctype: false
CheckAnchors: false
CheckLinks: false
CheckImages: false
CheckScripts: false
CheckMeta: false
CheckGeneric: false

# Email and phone
CheckMailto: false
CheckTel: false

# HTTPS enforcement
EnforceHTTPS: true

# Ignore common problematic external links
IgnoreURLs:
  - "github.com.*/issues/new"
  - "twitter.com"
  - "facebook.com"
  - "fonts.googleapis.com"
  - "fonts.gstatic.com"
  - "docs.microsoft.com"
  - "learn.microsoft.com"
  - ".pages.dev"

# Performance settings
ExternalTimeout: 10
HTTPConcurrencyLimit: 4
CacheExpires: "6h"

# Logging
LogLevel: 1
LogSort: "document"
OutputDir: "tmp/.htmltest.external"
OutputCacheFile: "refcache.json"
OutputLogFile: "htmltest.log"

# Cache settings
StripQueryString: true
StripQueryExcludes:
  - "fonts.googleapis.com"
  - "cdnjs.cloudflare.com"

# HTTP headers
HTTPHeaders:
  User-Agent: "htmltest/0.17.0 (+https://github.com/wjdp/htmltest)"
  Accept: "*/*"

RedirectLimit: 3
